# Generated by Django 4.2.9 on 2024-04-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name2',
            new_name='name',
        ),
    ]
